ManasDroid/Hacktoberfest2020

- CODE in C/Mathematical/Niven Number.c
Program to check whether given number is Niven number or not. Added under Mathematical in C language. Fixed #11
> Niven Number fixes #11

- CODE in C/Sorting/Bubble_sort.c
- CODE in C/Sorting/Insertion_sort.c
- CODE in C/Sorting/Merge_sort.c
- CODE in C/Sorting/Quick_sort.c
- CODE in C/Sorting/Selection_sort.c
> 5 sorting programs in c are added

- CODE in C/Data Structures/arrayRotation.java
java code to rotate the array by one in either direction
Fixes #46
> Fixes: rotate the array by one in either direction

- CODE in C/Data Structures/pointers_concept.c
Initially, "pointers_concept.c" was issuing a warning because of "abs()".
So, I included "stdlib.h" header file.
> Updated pointers_concept.c

- CODE in C/Data Structures/parenthesis using stack.py
I'm new to contributing in pre-existing open source and fluent in python. I did C++ long back although I mastered a lot and did projects in it. I switched to python for more than an year for Django, robotics and recently ML. Please accept this and assign this to me.
> Parenthesis check using stack in python

- README.md
Added Hacktoberfest- 2020 banner
Added badges
> Added Project Badges to README.md

- Factorial of a number using recursion
###Finding Factorial of a number using recursion
> Factorial-of-a-number-using-recursion.c

- java/NthNodeFromEndInnLinkedList.java
nth_position_from_end_in_linked_list_java_solution. @ManasDroid Pls review
> nth_position_from_end_in_linked_list_java_solution_issue_#_87

- Basic DSA qs/dutch_flag_sort.py
Segregating a set of 0's, 1's and 2's using the Dutch Flag Algorithm. #85
> 0, 1, 2 sort using Dutch Flag algorithm

- Stack/stack.cpp
- Stack/stack_operations_cpp.cpp
TASK: PROGRAM TO SORT A STACK 
THANKS @ManasDroid for assigning this task .
> SORTING A STACK IN C LANGUAGE 

- Stack/stack_operations_cpp.cpp
"TASK -implement stack using linked list "
I  had performed the task in cpp language .
thank you @ManasDroid for giving this opportunity to make me do this .
> STACK OPERATIONS IN CPP LANGUAGE

- CODE in C/Data Structures/queue using linked list
> Create queue using linked list

- LINKED LIST/merge_linkedlists.c
TASK: merge two sorted linked lists 
thank you @ManasDroid for assigning this to me .
> merged sorted linked lists

- Basic DSA qs/queueUsingLinkedList.cpp
- Basic DSA qs/stacksUsingLinkedList.cpp
With this code I have resolved the issue #91 and #90 
This is the code for implementing Queues using Linked Lists in C
This is the code for implementing Stacks using Linked Lists in C
Essentially I have used structures and pointer to structure objects
> Queues Using Linked List in C

- Basic DSA qs/HRbitwise.c
C problem to solve tower of hanoi using recursion
> tower of hanoi 

- CODE in C/Data Structures/Swap_two_nodes.cpp
Swap two nodes in a linked list. The code can handle multiple number of test case at the same time.
> Swap_two_nodes.cpp

- java/MergeTwoSortedLinkedList.java
> merged_two_sorted_linked_list_java_solution_#_#89

- Basic DSA qs/tower_of_hanoi.cpp
I have resolved ths issue #86 for Towers Of Hanoi in C++(C).
I have used Recurrsion in this code
thanks
> TowerOfHanoi_by_sid-1207_Cpp

- Basic DSA qs/bhavya092-queue-using-LL-CPP.cpp
C++ code for creating a Queue using LinkedList.
A menu-driven program to enqueue,dequeue elements along with viewing the list.
Resolved issue #91
> bhavya092-queue-using-LL-CPP

- print_rectangle_pattern.c
C program to print solid rectangle star pattern
> Create a program to print_rectangle_pattern

- Basic DSA qs/LinkedQueueImplement.java
> Queue using Linked list

- Basic DSA qs/stack using linked list
- stack using linked list
stack using linked list in c language
> stack using linked list

- a program to merge two sorted linked list
[A program to merge two sorted linked list.txt](https://github.com/ManasDroid/Hacktoberfest2020/files/5397586/A.program.to.merge.two.sorted.linked.list.txt)
> Created a program to merge two sorted linked list

- CODE in C/Data Structures/Binary Search Tree.cpp
- CODE in C/Data Structures/Doubly Linked List.cpp
Adding Binary Search Tree with the following functionalities ---
1> Create a Binary Search Tree through Insertion
2> Deletion of Node
3> Searching a Node with Value
4> Finding the min and max value in a Tree
5> PreOrder, PostOrder and Inorder Traversal
> Adding Binary Search Tree and Doubly Linked List

- Print Prime Fibonacci Series.py
This program print only the prime Fibonacci list elements.
> Prime Fibonacci Series

- Queue/Queue_using_Array
The code shows the implementation of stack using arrays. All the basic operations that can be performed on a stack are being included in the code. the basic operations that are being included in the program are:
1.Insert
2.Delete
3.Display element at the front
4.Display all elements of the queue
Hope you like it....
> Queue_using_Array
